###
GET http://localhost:3002/api/cars HTTP/1.1


###
POST http://localhost:3002/api/cars HTTP/1.1
Content-type: application/json

{
  "  color":"red",
      " make": "VW",
       " model":" Polo-GTI",
    "   reg_number": "CA 5550"
}


###

DELETE http://localhost:3002/api/cars/CL 61045 HTTP/1.1


  